config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  get "home", to: "application#home"

  get '/signup', to: "users#new"
  resources :users, except: [:new] do
  	resources :pets
    resources :posts, only: :index
  end

  resources :pets do
    resources :posts, only: [:new, :create, :edit, :destroy, :index, :show]
  end

  resources :posts do
    resources :comments, only: [:create]
  end


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback', to: 'authorizations#create'

  # get '/welcome', to: 'authorizations#welcome'

end

app/models/pet.rb
class Pet < ApplicationRecord
	has_many :posts
	belongs_to :user
	validates :user, presence: true
	validates :name, presence: true
	validates :species, presence: true
	validates :breed, presence: true

	def self.search(search)
  	where("name LIKE ? OR species LIKE ? OR breed LIKE ?", "%#{search}%", "%#{search}%", "%#{search}%") 
	end

	# def top_three_pets
 #  	pets = Pet.includes(:posts).limit(3)
 #  	pets.flat_map do |pet|
 #     pet.posts.count
 #  	end
	# end

end

app/controllers/pets_controller.rb
class PetsController < ApplicationController
	before_action :set_pet, only: [:show, :edit, :update, :destroy]
	
	def new
		@pet = Pet.new
	end

	def create
		# binding.pry
		@pet = Pet.new(pet_params)
		if @pet.save
			flash[:success] = "Your pet has been saved successfully!"
			redirect_to pet_path(@pet)
		else
			flash[:danger] = "Your pet failed to save"
			render "new"
		end
	end

	def show
	end

	def index
		if params[:search]
	  	@pets = Pet.search(params[:search])
	  	elsif @pets = if params[:user_id]
      	user = User.find(params[:user_id])
      	user.pets.page(params[:page]).per_page(5)
      else
    		@pets = Pet.paginate(page: params[:page], per_page: 15)
    	end
    else
   		@pets = Pet.all
   	end	
  end



	def edit
	end

	def update
		if @pet.update(pet_params)
			flash[:success] = "Your pet was successfully edited"
			redirect_to pet_path
		else
			flash[:danger] = "Your pet has not been updated"
			render "edit"
		end
	end

	def destroy
		@pet.delete
		redirect_to pets_path
	end

	private

	def set_pet
		@pet = Pet.find_by(id: params[:id])
	end


	def pet_params
		params.require(:pet).permit(:name, :species, :breed, :user_id)
	end


end

app/views/pets/edit.html.erb
<%= render 'shared/errors', obj: @pet %>

<h1>Edit Pet</h1>

<%= form_for @pet do |f| %>

	<%= f.hidden_field :user_id, value: current_user.id %>
	Name: <%= f.text_field :name, :value => @pet.name %><br />
  Species : <%= f.text_field :species, :value => @pet.species %><br />
  Breed : <%= f.text_field :breed, :value => @pet.breed %><br />
  <%= f.submit "Edit Pet"%>

<% end %>

app/views/pets/index.html.erb
<% if @pets.blank? %>
  <h4>There are no pets matching the term <%= params[:search] %>.</h4>
<% end %>


<!-- 	<% if current_user %>
		<h2><%= "#{current_user.name}'s Pets" %></h2>

		<ul>
			<% current_user.pets.each do |pet| %>
			<li> <strong><%= link_to "#{pet.name}", pet_path(pet) %></strong> <br> <%= pet.breed %> <br> <%= pet.species %> <br>
				<small><%= link_to "Edit Pet", edit_pet_path(pet) %> &nbsp &nbsp 
				<%= link_to "Delete Pet", pet, method: :delete, data: { confirm: 'Are you sure you want to delete this pet?' } %>
				</small> <br> <br>
			</li>
			<% end %>
		</ul>

		<%= "#{current_user.name}'s" %> Total Pets: <%= current_user.pets.count %> <br> <br>


		<%= link_to "Add A Pet", new_user_pet_path(current_user) %> <br><br>
	<% end %>
		<hr />
 -->		

<h2>Pets</h2>
<ul>
<% if params[:user_id] %>
<%= "#{current_user.name}'s Pets" %>
<% end %>
<% @pets.each do |pet| %>
<li> <strong><%= link_to "#{pet.name}", pet_path(pet) %></strong> <br> <%= pet.breed %> <br> <%= pet.species %> <br>
</li>
	<% end %>
</ul>
<div align="center">
	<%= will_paginate %>
</div>

app/views/pets/new.html.erb
<%= render 'shared/errors', obj: @pet %>

<h1>New Pet</h1>

<%= form_for @pet do |f| %>

	<%= f.hidden_field :user_id, :value => current_user.id %>
	Name: <%= f.text_field :name, placeholder: "Pet's Name" %><br />
  Species : <%= f.text_field :species, placeholder: "Species" %><br />
  Breed : <%= f.text_field :breed, placeholder: "Breed" %><br />
  <%= f.submit %>

<% end %>

app/views/pets/show.html.erb
<% if current_user %>
<h2><strong> <%= current_user.name %>'s Pet'  </strong></h2>
<% end %>
<strong> <%= @pet.name %> </strong><br>
Species: <%= @pet.species %> <br>
Breed: <%= @pet.breed %> <br>
<br>

<% if current_user %>
	<small><%= link_to "Create new post about #{@pet.name}", new_pet_post_path(@pet) %> &nbsp &nbsp
	<%= link_to "Edit Pet", edit_pet_path(@pet) %> &nbsp &nbsp 
	<%= link_to "Delete Pet", @pet, method: :delete, data: { confirm: 'Are you sure you want to delete this pet?' } %> &nbsp &nbsp
	<%= link_to "#{current_user.name}'s Pets", pets_path %> &nbsp &nbsp
	</small>
<% end %>


<hr />
<ul>
<% @pet.posts.each do |post| %>
<li> <strong><%= link_to "#{post.title}", pet_post_path(@pet.id, post.id) %></strong> <br>
	<%= post.content %> <br>
	<small> <%= link_to "Edit Post", edit_pet_post_path(@pet, post) %> 
	<%= link_to "Delete Post", pet_post_path(@pet, post), method: :delete, data: { confirm: 'Are you sure?' } %>
	</small> <br><br>
</li>
<% end %> 
	
</ul>