config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  get "home", to: "application#home"

  get '/signup', to: "users#new"
  resources :users, except: [:new] do
  	resources :pets
    resources :posts, only: :index
  end

  resources :pets do
    resources :posts, only: [:new, :create, :edit, :destroy, :index, :show]
  end

  resources :posts do
    resources :comments, only: [:create]
  end


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback', to: 'authorizations#create'

  # get '/welcome', to: 'authorizations#welcome'

end

app/models/post.rb
class Post < ApplicationRecord
  validates :title, presence: true
  validates :content, presence: true
  belongs_to :user
  belongs_to :pet
  has_many :comments, dependent: :destroy
  has_many :commenters, through: :comments, source: :user
 	default_scope -> { order(updated_at: :desc) }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :set_post, only: [:show, :edit, :update, :destroy]
	before_action :require_user, except: [:index, :show]
	before_action :require_same_user, only: [:edit, :update, :destroy]

	def index
		@posts = if params[:user_id]
      user = User.find(params[:user_id])
      user.posts.page(params[:page]).per_page(5)
    else
    	@posts = Post.paginate(page: params[:page], per_page: 5)
    end
	end

	def new
		if params[:pet_id]
			@pet = Pet.find(params[:pet_id])
    	@post = @pet.posts.build
    	@post.pet = @pet 
    	# @post.user = current_user	
    else
    	@post = Post.new
    	# @post[:pet_id] = @pet.id
    	# @post.user = current_user
		end
	end

	def create
		@post = Post.new(post_params)
		# if params[pet_id]
	  @post.pet = Pet.find(params[:post][:pet_id])   
  # 	@post = @pet.posts.build(post_params)
  	@post.user = current_user  
  	if @post.save
    	flash[:success] = "Successfully created post."
    	# redirect_to pet_posts_path(@post.pet)
    	redirect_to user_pet_path(current_user.id, @post.pet.id)
  	else
   	 render :action => 'new'
  	end
	end

	def show
		@comment = Comment.new
		@comments = @post.comments.paginate(page: params[:page], per_page: 10)
	end

	def edit
	end

	def update
		if @post.update(post_params)
			flash[:success] = "Post was updated successfully!"
			redirect_to post_path
		else
			render 'edit'
		end
	end

	def destroy
		Post.find_by(id: params[:id]).destroy
		flash[:success] = "Post deleted successfully!"
		redirect_to posts_path
	end

	private

		def post_params
			params.require(:post).permit(:title, :content, :user_id, :pet_id)
		end

		def set_post
			@post = Post.find_by(id: params[:id])
		end

		def require_same_user
			if current_user != @post.user && !current_user.admin?
				flash[:danger] = "You can only edit or delete your own posts"
				redirect_to posts_path
			end
		end
end

app/views/posts/_commenters.html.erb
<!-- <h2>Comments</h2> -->
<% @post.comments.each do |comment| %>
  <p>
    <strong>Commenters:</strong>
    <%= comment.users.uniq.size %>
  </p>
 
<% end %>

app/views/posts/_form.html.erb
<%= render 'shared/errors', obj: @post %>

<div class="row">
  <div class="col-md-12">
<%= form_for @post do |f| %>

  
  <div class="field">
    <div class="form-group">
      <div class="control-label col-md-2">
      <strong><%#= f.label :pet_name %></strong><br> &nbsp
      <%#= binding.pry %>
      <%# if !params[:pet_id] %>
      <strong><%= f.label :pet_name %></strong> &nbsp
      <%= f.collection_select(:pet_id, current_user.pets.uniq, :id, :name, :prompt=>"Existing Pets") %>
      <% #else %>
      <%# binding.pry %>
      <%#= f.hidden_field :pet_id, :value => params[:pet_id] %>
      <strong><%#= f.label :pet_name %></strong>&nbsp
      <strong><%#= @pet.name %></strong>
      <br> &nbsp
      <%= link_to "Add Pet", new_user_pet_path(current_user) %>
      <%#= f.hidden_field :user_id, :value => current_user.id %>
      <%#= f.text_field :"#{@post.pet.name}" %>
      
      <%# end %>
      <%#= link_to "Add Pet", new_user_pet_path(current_user) %>
      <%#= link_to "Edit Pet", edit_user_pet_path(current_user) %>
      <strong><%#= f.label :pet_name  %></strong><br>
      <strong><%#= f.label :pet_name %></strong>
      <%#= f.text_field :pet_id, placeholder: "Pet's Name" %>
      <%#= f.text_field :pet_id, placeholder: "Pet's Species" %>

      <strong><%#= f.label :pet_breed %></strong>
      <%#= f.text_field :pet_id, placeholder: "Pet's Breed" %>
    </div>
    <div class="control-label col-md-2">
      <strong><%#= f.label :pet_breed %></strong>
      <%# binding.pry %>
      <strong><%#= f.label :pet_name  %></strong>
      <%#= f.text_field :pet_id, placeholder: "Pet's Name" %>
    </div>
  </div>
    </div>

<div class="form-group">
  <div class="control-label col-md-2">
    <%= f.label :title %>
  </div>
  <div class="col-md-8">
    <%= f.text_field :title, class: "form-control", placeholder: "Title of post", autofocus: true %>
</div>
  </div>
    <div class="form-group">
      <div class="control-label col-md-2">
        <%= f.label :content %>
      </div>
      <div class="col-md-8">
        <%= f.text_area :content, rows: 10, class: "form-control", placeholder: "Tell us about your pet." %>
      </div>
    </div>
    <div class="form-group">
      <div class="col-md-offset-2 col-md-10">
        <%= f.submit class: "btn btn-primary btn-lg btn-xlarge" %>
      </div>
    </div>
    <% end %>
    <div class="col-md-4 col-md-offset-4 colormatch">
      [ <%= link_to "Cancel request and return to posts listings", posts_path %> ]
    </div>
  </div>
</div>

app/views/posts/_post.html.erb
<% obj.each do |post| %>
  <div class="row">
    <div class="col-md-2">
      <section class="center">
      </section>
    </div>
    <div class="col-md-8 well">
      <h4><%= link_to "#{post.title}", post_path(post) %></h4>
      <small><p><%= "#{post.pet.name} | #{post.pet.species} | #{post.pet.breed}" %></p></small>
      <p><%= truncate(post.content, length: 150) %></p>
      <p>
        <span class="quiet"><small>Created 

        <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name.capitalize %> | <%= pluralize(post.comments.count, 'Comment') %> <br>
        <% if post.created_at != post.updated_at %>
        Updated <%= time_ago_in_words(post.updated_at) %> ago
        <% end %>
        </small></span>
      </p> 
      <% if logged_in? && (current_user == post.user || current_user.admin?) %>
      <div class="post-actions">
        <%= link_to "Edit this post", edit_post_path(post), class: "btn btn-xs btn-warning" %>
        <%= link_to "Delete this post", post_path(post), method: :delete, data: { confirm: "Are you sure you want to delete this post?" }, class: "btn btn-xs btn-danger" %>
      </div> <br><br>
      <% end %>
    </div>
  </div>
<% end %>

app/views/posts/edit.html.erb
<%= render 'shared/page_title', title: "Edit Existing Post" %>

<%= render "form" %>

app/views/posts/index.html.erb
<%= render 'shared/page_title', title: 'Listing All Posts' %>

<div align="center">
	<%= will_paginate %>
</div>
<%= render 'post', obj: @posts  %>
<div align="center">
	<%= will_paginate %>
</div>

app/views/posts/new.html.erb
<%= render 'shared/page_title', title: "Share Your Pet's Special Qualities" %>

<%= render "form" %>

app/views/posts/show.html.erb
<%= render 'shared/page_title', title: @post.title %>


<div class="well col-md-8 col-md-offset-2">
  <h4 class="center description"><strong><%= @post.pet.name %> <br> <%= @post.pet.species %>:  <%= (@post.pet.breed) %></strong></h4>
<hr /> 
<%= simple_format(@post.content) %>
<hr />
<div class="pull-right">
  <p class="center">
  	<em> Created by: </em>
    <small><%= @post.user.name %></small> <br><br>
    Comments: <%= @post.comments.size %>  &nbsp &nbsp Commenters: <%= @post.commenters.uniq.size %>
  </p>
  
  <p>
  	
  	<div class="pull-right">
        <%= time_ago_in_words(@post.created_at) %> ago <br>
        <% if @post.created_at != @post.updated_at %>
        Updated <%= time_ago_in_words(@post.updated_at) %> ago
        <% end %>
     </div><br>
   </p>
 </div>
</div>
<div class="user-actions">
  <% if logged_in? && (current_user == @post.user || current_user.admin?)%>
  <%# binding.pry %>
    <%= link_to "Edit this post", edit_post_path(@post), 
                              class: "btn btn-xs btn-warning" %>
    <%= link_to "Delete this post", post_path(@post), 
                        method: :delete,
      data: { confirm: "Are you sure you want to delete this post?" },
                                      class: "btn btn-xs btn-danger" %>
  <% end %>                                  
  <%= link_to "Return to posts listing", posts_path, 
                                class: "btn btn-xs btn-primary" %>
</div>
<% if logged_in? %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <h3>Comments: </h3>
      <hr />
  <%= form_for ([@post, @comment]) do |f| %>
      <div class="form-group">
        <div class="control-label col-md-2">
        <%= f.label :description, "Comment" %>
      </div>
      <div class="col-md-8">
        <%= f.text_area :description, rows: 8, class: "form-control", placeholder: "Enter Comment Here" %>
      </div>
      <div class="form-group">
        <div class="col-md-offset-2 col-md-10">
          <%= f.submit "Submit Comment", class: "btn btn-primary btn-lg btn-xlarge" %>
        </div>
      </div>
    <% end %>
    <hr />
   </div>
  </div>
<% end %>
   




<% if @post.comments != 0 %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2">
      <!-- <h3>Prior Comments:</h3>   -->
        <div id="messages">
          <%= render partial: 'comments/comments', object: @comments %>
        </div>
    </div>
  </div>
<% else %>
  <div class="row">
    <div class="col-md-8 col-md-offset-2"></div>
    <h3> No Comments Yet! </h3>
    </div>
  </div>
<% end %>