config/routes.rb
Rails.application.routes.draw do
  root "application#home"
  get "home", to: "application#home"

  get '/signup', to: "users#new"
  resources :users, except: [:new] do
  	resources :pets
    resources :posts, only: :index
  end

  resources :pets do
    resources :posts, only: [:new, :create, :edit, :destroy, :index, :show]
  end

  resources :posts do
    resources :comments, only: [:create]
  end


  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/auth/google_oauth2/callback', to: 'authorizations#create'

  # get '/welcome', to: 'authorizations#welcome'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception
	helper_method :current_user, :logged_in?

  def home
    # redirect_to posts_path if logged_in?
  end

  def current_user
  	@current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
  	!!current_user
  end

  def require_user
  	if !logged_in?
  		flash[:danger] = "You must be logged in to perform that action"
  		redirect_to root_path
  	end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/application/home.html.erb
<div class="jumbotron center">
  <h1>Welcome To Pet Props!</h1>
  <h2>The Site For Pet Lovers!</h2><br><br>
  <% if !logged_in? %>
  <p><%= link_to "Sign Up", signup_path, class: "btn semi-transparent-button btn-lg" %> &nbsp  &nbsp  &nbsp <%= link_to "Log In", login_path, class: "btn semi-transparent-button btn-lg" %> &nbsp &nbsp &nbsp <%= link_to "Log In Using Google", '/auth/google_oauth2', method: :post, class: "btn semi-transparent-button btn-lg" %></p>
  <% end %>
</div>

<div class="row">
  <div class="col-lg-4">
    <% @post = Post.first %>
    <h2><%= @post.title %></h2>
    <p><%= @post.content %></p>
    <p><div class="btn btn-primary btn-xxlarge btn-home" > <%= link_to "View details »", post_path(@post)  %></div></p>
  </div>
  <div class="col-lg-4">
    <% @post = Post.second %>
    <h2><%= @post.title %></h2>
    <p><%= @post.content %></p>
    <p><div class="btn btn-primary btn-xxlarge"> <%= link_to "View details »", post_path(@post)  %></div></p>
 </div>
  <div class="col-lg-4">
    <% @post = Post.third %>
    <h2><%= @post.title %></h2>
    <p><%= @post.content %></p>
    <p><div class="btn btn-primary btn-xxlarge"> <%= link_to "View details »", post_path(@post)  %></div></p>
  </div>
</div>